config/routes.rb
# Rails.application.routes.draw do
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
#   # Can be used by load balancers and uptime monitors to verify that the app is live.
#   get "up" => "rails/health#show", as: :rails_health_check

#   # Render dynamic PWA files from app/views/pwa/*
#   get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
#   get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

#   # Defines the root path route ("/")
#   # root "posts#index"

# end

Rails.application.routes.draw do
 	root to: "companies#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
	
	resources :companies do 
 		member do
 			get :employees
 		end
 	end
 	
 	resources :employees 

 	resources :reimbursements do 
 		member do
 			post :download
 		end
 	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	validates :company_name, uniqueness: true, presence: true
	belongs_to :user
	has_many :employees
	has_many :reimbursements
end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :company
	belongs_to :user
	has_many :reimbursements, inverse_of: :employee
	validates :name, :date_of_birth, :qualification, :designation, :email, presence: true
	validates :email, format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/ }
	before_validation :set_user_id 
	def set_user_id
		self.user_id = self.company.user_id
	end
end

app/models/reimbursement.rb
class Reimbursement < ApplicationRecord
  has_one_attached :receipt
  belongs_to :employee, inverse_of: :reimbursements 
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :companies
  has_many :employees
  validates :email, format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/ }
  def self.from_omniauth(auth)
  	@user = User.find_or_create_by(email: auth["email"]) do |user|
			user.name = auth["name"]
			user.first_name = auth["first_name"]
			user.last_name = auth["last_name"]
			user.image_url = auth["image"]
			user.password = auth["email"].split("@")[0]
		end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_company, only: [:update, :show, :destroy, :edit, :employees]
  skip_before_action :verify_authenticity_token, only: :employees

  def index
    @companies = current_user.companies.includes(:employees, :reimbursements).paginate(page: params[:page], per_page: 10)
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id
    if @company.save
      flash[:notice] = "Successfully Created Company."
      redirect_to companies_path 
    else
      render action: 'new' 
    end
  end

  def update
    if @company.update(company_params)
      flash[:notice] = "Successfully Updated."
      redirect_to companies_path 
    else
      render action: 'edit' 
    end
  end

  def show
    @employees = @company.employees.includes(:reimbursements).paginate(page: params[:page], per_page: 10)
  end

  def edit
  end

  def destroy
    if @company.destroy!
      flash[:notice] = "Successfully Deleted."
      redirect_to companies_path
    else
      flash[:alert] = "Unable to delete company"
      redirect_to companies_path
    end
  end

  def employees
    render json: @company.employees
  end

  private
  def company_params
    params.require(:company).permit(:company_name, :user_id, :description)
  end

  def find_company
    @company = Company.find(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_employee, only: [:update, :show, :destroy, :edit]

  def index
    @employees = current_user.employees.paginate(page: params[:page], per_page: 10)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to company_path(@employee.company), notice: "Employee has been created successfully."
    else
      render action: 'new'
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to company_path(@employee.company), notice: "Employee details has been updated successfully." 
    else
      render action: 'edit' 
    end
  end

  def show
    @reimbursements = @employee.reimbursements.paginate(page: params[:page], per_page: 10)
  end

  def edit
  end

  def destroy
    if @employee.destroy!
      flash[:notice] = "Employee deleted successfully."
    else
      flash[:alert] = "Unable to delete company"
    end
    redirect_to company_path(@employee.company)
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :qualification, :age, :designation, :email, :company_id, :date_of_birth)
  end

  def find_employee
    @employee = Employee.find(params[:id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/controllers/reimbursements_controller.rb
class ReimbursementsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_reimbursement, only: [:update, :show, :destroy, :edit, :download]
  skip_before_action :verify_authenticity_token, only: :download
  def index
    @reimbursements = Reimbursement.includes(:employee, :company).where(employee: {user_id: current_user.id}).paginate(page: params[:page], per_page: 10)
  end

  def new
    @reimbursement = Reimbursement.new
  end

  def create
    reimbursement = Reimbursement.new(reimbursement_params)
    if reimbursement.save
      redirect_to reimbursements_path, notice: "Reimbursement created successfully"
    else
      render action: 'new'
    end
  end

  def update
    if @reimbursement.update(reimbursement_params)
      redirect_to reimbursements_path, notice: "Reimbursement has been updated successfully." 
    else
      render action: 'edit' 
    end
  end

  def show
  end

  def edit
  end

  def destroy
    if @reimbursement.destroy!
      flash[:notice] = "Reimbursement deleted successfully."
    else
      flash[:alert] = "Unable to delete Reimbursement"
    end
    redirect_to company_path(@reimbursement.company)
  end

  def download
    #TODO
    # rails_blob_path(@reimbursement.receipt, disposition: "attachment")
    # url = @reimbursement.receipt.url
    # redirect_to url
    # data = open(url) 
    # send_data data.read, filename: "NAME YOU WANT.pdf", type: "application/pdf", disposition: 'inline', stream: 'true', buffer_size: '4096' 
    # s3 = Aws::S3::Resource.new(
    #   region: 'us-east-1',
    #   access_key_id: "",
    #   secret_access_key: ""
    # )
    # s3.bucket('rails-active-storage-claims').object('key').download_file(url)
  end

  private
  def reimbursement_params
    params.require(:reimbursement).permit(:purpose, :amount, :date_of_expenditure, :company_id, :employee_id, :receipt)
  end

  def find_reimbursement
    @reimbursement = Reimbursement.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def google_oauth2
		@user = User.from_omniauth(auth)
		if @user.persisted?
	    flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
		else
			session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_session_path, alert: "Oops! Something went wrong, Please try after sometime" #@user.errors.full_messages.join("\n")
		end
	end

	private
	def auth
		request.env['omniauth.auth']['info']
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<div class="d-flex justify-content-center my-2">
	<div class="card shadow">
		<div class="card-header">New Company</div>
		<div class="card-body">
			<%= form_with model: @company do |f| %>
				<ul>
					<% @company.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
				</ul>
			  <div class="form-group">
			  	<%= f.label :company_name%>
					<%= f.text_field :company_name, class: "form-control" %>
			  </div>
        <div class="form-group">
        	<%= f.label :description %>
					<%= f.text_area :description, class: "form-control" %>
        </div>
			  <div class="form-group">
			  	<%= f.submit "Save", class: "btn btn-primary"%>
			  </div>
			<% end %>
		</div>
	</div>
</div>

<style type="text/css">
	.card {
		width: 500px;
	}
</style>

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/destroy.html.erb
<h1>Companies#destroy</h1>
<p>Find me in app/views/companies/destroy.html.erb</p>

app/views/companies/edit.html.erb
<%= render 'form' %>

app/views/companies/index.html.erb
<div class="card shadow">
	<div class="card-body">
		<%= link_to "+ Add Company", new_company_path, class: "btn btn-primary mb-2 float-right"%>
		<table class="table table-striped table-hover">
			<thead class="thead-dark">
				<th>#</th>
				<th>Company Name</th>
				<th>Owner</th>
				<th>Employee Count</th>
				<th>Total Reimbursements</th>
				<th>Total Amount</th>
				<th>Actions</th>
			</thead>
			<tbody>
				<%if @companies.present? %>
					<% @companies.each_with_index do |company, i|%>
						<tr>
							<td><%= i+1%></td>
							<td>
								<%= link_to company.company_name, company_path(company) %>
							</td>
							<td>
								<%= company.user.name %>
							</td>
							<td>
								<%= company.employees.length %>
							</td>
							<td>
								<%= company.reimbursements.length %>
							</td>
							<td>
								<%= company.reimbursements.map(&:amount).inject(:+) || 'N/A' %>
							</td>
							<td class="actions d-flex justify-content-space-between">
								<%= link_to company_path(company) do%>
									<i class="fa fa-eye"></i>
								<% end %>
								<%= link_to edit_company_path(company) do %>
									<i class="fa fa-edit"></i>
								<% end %> 						
								<%= button_to company_path(company), method: :delete do%>
									<i class="fa fa-trash-o"></i>
								<% end %>

							</td>
						</tr>
					<%end%>
				<%else%>
					<tr><td colspan="7">
						No companies found
					</td></tr>
				<% end %>
			</tbody>
		</table>
		<%= will_paginate @companies%>
	</div>
</div>

<style type="text/css">
	.actions a{
 		padding: 3px;
 	}
 	.actions i{
 		width: 20px;
 		height: 20px;
 	}
</style>

app/views/companies/new.html.erb
<%= render 'form' %>

app/views/companies/show.html.erb
<div class="d-flex flex-column p-2">
	<h2><%= @company.company_name %></h2>
	<span class="mx-5 my-2"><%= @company.description.capitalize %></span>
</div>
<%= render :partial => 'employees/list', locals: {employees: @employees, company_id: @company.id} %>

app/views/companies/update.html.erb
<h1>Companies#update</h1>
<p>Find me in app/views/companies/update.html.erb</p>

app/views/employees/_form.html.erb
<div class="d-flex justify-content-center my-2">
	<div class="card shadow">
		<div class="card-header">New Employee</div>
		<div class="card-body">
			<%= form_with model: @employee do |f| %>
				<% if @employee.errors.any?%>
					<ul>
						<% @employee.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
					</ul>
				<% end %>
				<div class="form-group">
					<%= f.label :employee_name%>
					<%= f.text_field :name, class: "form-control" %>
				</div>
				
				<div class="form-group">
					<%= f.label :qualification %>
					<%= f.text_field :qualification, class: "form-control" %>
				</div>
				
				<div class="form-group">
					<%= f.label :date_of_birth %>
					<%= f.date_field :date_of_birth, class: "form-control"%>
				</div>
				
				<div class="form-group">
					<%= f.label :email %>
					<%= f.text_field :email, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :designation %>
					<%= f.text_field :designation, class: "form-control" %>
				</div>

				<div class="form-group">
					<% if params["company_id"].present?%>
						<%= f.hidden_field :company_id, value: params["company_id"] %>
					<% else %>
						<%= f.label :select_company %>
						<%= f.collection_select(:company_id, current_user.companies, :id, :company_name, {:prompt => false}, { class: "form-control"})%>
					<% end  %>
				</div>
				<div class="form-group">
					<%= f.submit "Save", class: "btn btn-primary" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<style type="text/css">
	.card {
		width: 500px;
	}
</style>

app/views/employees/_list.html.erb
<div class="card shadow">
	<div class="card-body">
		<% if company_id.present? %>
			<%= link_to "+ Add Employee", new_employee_path(company_id: company_id), class: "btn btn-primary mb-1 float-right"%>
		<% else %>
			<%= link_to "+ Add Employee", new_employee_path(company_id: nil), class: "btn btn-primary mb-1 float-right"%>
		<% end %>
		<div class="table-responsive">
			<table class="table table-striped table-hover">
			<thead class="thead-dark">
				<tr>
					<th> # </th>
					<th>Name</th>
					<th>Email</th>
					<th>Designation</th>
					<th>Total Reimbursements</th>
					<th>Total Amount</th>
					<% if params[:action] == "index" %>
						<th>Company</th>
					<% end %>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
			  <% if employees.present? %>
					<% employees.each_with_index do |employee, i| %>
						<tr>
							<td> <%=i+1%></td>
							<td><%= employee.name %></td>	
							<td><%= employee.email %></td>
							<td><%= employee.designation %></td>
							<td><%= employee.reimbursements.length%></td>
							<td><%= employee.reimbursements.map(&:amount).inject(:+) || 'N/A'%></td>
							<% if params[:action] == "index" %>
								<td><%= employee.company.company_name %></td>
							<% end %>
							<td class="actions d-flex justify-content-space-between">
								<%= link_to employee_path(employee) do %>
									<i class="fa fa-eye"></i>
								<% end %>
								<%= link_to edit_employee_path(employee) do %>
									<i class="fa fa-edit"></i>
								<% end %>
								<%= button_to employee_path(employee), method: :delete do %>
									<i class="fa fa-trash-o"></i>
								<% end %>
							</td>
						</tr>
					<% end %>
				<%else%>
					<tr>
						<td colspan="8">
							No employees found
						</td>
					</tr>
				<%end%>
			</tbody>
		</table>	
		</div>
		
		<%= will_paginate employees%>
	</div>
</div>

<style type="text/css">
	.actions a{
 		padding: 3px;
 	}
 	.actions i{
 		width: 20px;
 		height: 20px;
 	}
</style>

app/views/employees/edit.html.erb
<%= render 'form' %>

app/views/employees/index.html.erb
<%= render :partial => 'list', locals: {employees: @employees, company_id: nil} %>

app/views/employees/new.html.erb
<%= render 'form' %>

app/views/employees/show.html.erb
<div class="card shadow-lg">
    <div class="card-body">
			<div class="row d-flex mb-2">
				<div class="col-sm-2">
					<h3 class="card-title"><%= @employee.name.capitalize%></h3>
				</div>
				<div class="offset-1 col-sm-3 align-content-center">
					<b>Email:</b> <%= @employee.email%>
				</div>
				<div class="offset-1 col-sm-3 align-content-center">
					<b>DOB:</b> <%= @employee.designation%>
				</div>
			</div>

			<div class="row d-flex">
				<div class="offset-2 col-sm-3 align-content-center">
					<b>Company:</b>
					<%= @employee.company.company_name%>
				</div>
				<div class="offset-1 col-sm-2 align-content-center">
					<b>Qualification:</b> <%= @employee.qualification%>
				</div>
				<div class="offset-1 col-sm-3 align-content-center">
					<b>Designation:</b> <%= @employee.date_of_birth%>
				</div>
			</div>

    </div>
</div>
<%= render :partial => 'reimbursements/list', locals: {reimbursements: @reimbursements} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ReimbursementApp</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 800px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
    img {
      max-height: 50px;
    }
    .navbar .navbar-nav .nav-link {
        color: azure; 
    }

    .logout, .login{
      border-radius: 25px;
    }

    a:hover {
      text-decoration: none;
    }

    p{
      font-weight: bold;
      margin: 0px;
    }
    span {
      font-size: 12px;
    }
  </style>
</head>
<body>

  <nav class="navbar navbar-expand-lg bg-primary navbar-dark justify-content-between">
    <div>
      <img src = "/refund.jpg" alt="no-image">
      <a class="navbar-brand" href="#">ReimbursementApp</a>
    </div>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item nav-link" >
          <%= current_user.email %>
        </li>
        <li class="nav-item nav-link" >
          <% if current_user.image_url.present?%>
            <%= image_tag current_user.image_url, :height => '30px', :width => '30px', style: "border-radius: 20px", alt: 'No image' %>
          <% else %>
            <i class="fa fa-user-circle"></i>
          <% end %>
        </li>
        <li class="nav-item align-content-center">
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-light logout" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= button_to "Login", new_user_session_path, class: "btn btn-light login" %>
        </li>
      <% end %>
    </ul>
  </nav>

  <div class="container-fluid">
    <div class="row content">
      <% if user_signed_in?%>
        <div class="col-sm-2 sidenav">
          <ul class="list-group list-group-flush mt-2">
            <li class="list-group-item list-group-item-light"><%= link_to "Companies", companies_path,  class: "nav-link" %></li>
            <li class="list-group-item list-group-item-light"><%= link_to "Employees", employees_path, class: "nav-link" %></li>
            <li class="list-group-item list-group-item-light"><%= link_to "Reimbursements", reimbursements_path, class: "nav-link"%></li>
          </ul>
        </div>
        <div class="col-sm-10 mt-2">
          <div class="notification">  
            <% if notice.present? %>
              <p class="alert alert-success alert-dismissible fade show"><%= notice %>
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
              </p>
            <% elsif alert.present? %>
              <p class="alert alert-warning alert-dismissible fade show"><%= alert %>
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
              </p>
            <%end%>
          </div>
          <%= yield%>
        </div>
      <% else %>
        <div class="col-sm-12">
          <%= yield %>
        </div>
      <% end %>
    </div>
  </div>

  <footer>
    <div class="d-flex justify-content-center">© 2024 ReimbursementApp, All rights reserved</div>
    <hr/>
    <div class="d-flex justify-content-between">
      <div>
        <p>Phone</p> 
        <span>+91 9886524174</span>
      </div>
        
      <div>
        <p>Email </p>
        <span>ramya20lu@gmail.com</span>
      </div>
      <div>
        <p>Follow Me</p>

        <a href="https://www.linkedin.com/in/ramya2b9144179/">
          <li-icon type="app-linkedin-bug-color-icon" class="ivm-view-attr__icon  " size="large" role="img" aria-label="LinkedIn">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" data-supported-dps="24x24" fill="black" class="mercado-match" width="24" height="24" focusable="false">
              <path d="M20.5 2h-17A1.5 1.5 0 002 3.5v17A1.5 1.5 0 003.5 22h17a1.5 1.5 0 001.5-1.5v-17A1.5 1.5 0 0020.5 2zM8 19H5v-9h3zM6.5 8.25A1.75 1.75 0 118.3 6.5a1.78 1.78 0 01-1.8 1.75zM19 19h-3v-4.74c0-1.42-.6-1.93-1.38-1.93A1.74 1.74 0 0013 14.19a.66.66 0 000 .14V19h-3v-9h2.9v1.3a3.11 3.11 0 012.7-1.4c1.55 0 3.36.86 3.36 3.66z"></path>
            </svg>
          </li-icon>
        </a>
      </div>
      <div>
        <p>Built By</p>
        <span><b>Ramya L U,</b> using Ruby on Rails</span>
      </div>
    </div>
    <hr/>
    <div class="container-fluid">
      <h2 class="pull-right">CONTACT US</h2>
      <hr/>
      <div class="row">
        <div class="col-sm-5">
          <p>Contact us and we'll get back to you within 24 hours.</p>
          <span>Bangalore, India</span>
        </div>
        <div class="col-sm-7">
          <div class="row">
            <div class="col-sm-6 form-group">
              <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
            </div>
            <div class="col-sm-6 form-group">
              <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
            </div>
          </div>
          <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
          <div class="row">
            <div class="col-sm-12 d-flex justify-content-center">
              <button class="btn btn-primary" type="submit">Send</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </footer>
</body>
</html>


<script type="text/javascript">
  setTimeout(function() {
    document.querySelector('.alert').remove();
  }, 3000);
</script>

app/views/reimbursements/_form.html.erb
<div class="d-flex justify-content-center my-2">
	<div class="card shadow">
		<div class="card-header">New Reimbursement</div>
		<div class="card-body">
			<%= form_with model: @reimbursement do |f| %>
				<% if @reimbursement.errors.any?%>
					<ul>
						<% @reimbursement.errors.full_messages.each do |message| %>
					        <li><%= message %></li>
					    <% end %>
					</ul>
				<% end %>
				<div class="form-group">
					<%= f.label :company %>
					<%= f.collection_select(:company_id, current_user.companies, :id, :company_name, { :prompt => "Select company"}, { class: "form-control"}) %>
				</div>
				<div class="form-group">
				<%= f.label :select_employee %> 
				<%= f.collection_select(:employee_id, [], :id, :name, {:prompt => "Select employee"}, { class: "form-control"}) %>
				<!-- search employee --- <select id="employee_select"></select> -->
				</div>
				<div class="form-group">
					<%= f.label :purpose%>
					<%= f.text_area :purpose, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :amount %>
					<%= f.number_field :amount, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :date_of_expenditure %>
					<%= f.date_field :date_of_expenditure, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :receipt%>
					<%= f.file_field :receipt, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.submit "Save", class: "btn btn-primary" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script type="text/javascript">
	$('#reimbursement_company_id').change(function(){
		const company_id = $('#reimbursement_company_id').val()
		$.get(`/companies/${company_id}/employees`, function(data, status){
			var options = ['<option value=#>Select employee</option>'];
			data.forEach(employee => options.push(`<option value=${employee.id}>${employee.name}</option>`) )

			var select_tag = `<select name="reimbursement[employee_id]" id="reimbursement_employee_id">${options}</select>`;
		 	var employeesHandler = document.getElementById('reimbursement_employee_id');
		 	employeesHandler.innerHTML = select_tag;
		})
	})
</script>

app/views/reimbursements/_list.html.erb
<div class = "card shadow">
	<div class="card-body">
		<%= link_to "+ Add Reimbursement", new_reimbursement_path, class: "btn btn-primary mb-1 float-right"%>
		<table class="table table-striped table-hover">
			<thead class="thead-dark">
				<tr>
					<th>#</th>
					<th>Purpose</th>
					<th>Amount</th>
					<th>Date Of Expenditure</th>
					<th>Company</th>
					<th>Employee</th>
					<th>Receipt</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
			  <% if reimbursements.present? %>
					<% reimbursements.each_with_index do |reimbursement, i| %>
						<tr>
							<td><%= i + 1%></td>
							<td><%= reimbursement.purpose %></td>	
							<td><%= reimbursement.amount %></td>
							<td><%= reimbursement.date_of_expenditure%></td>
							<td><%= reimbursement.company.company_name.capitalize%></td>
							<td><%= reimbursement.employee.name.capitalize %></td>
							<td>
								<i class="fa fa-download" id="download-receipt" reimbursement-id="<%=reimbursement.id%>" onclick="download_receipt(this)"></i></td>
							<td class="actions d-flex justify-content-space-between">
								<%#= link_to reimbursement_path(reimbursement) do %>
									<!-- <i class="fa fa-eye"></i> -->
								<%# end %>
								<%= link_to edit_reimbursement_path(reimbursement) do %>
									<i class="fa fa-edit"></i>
								<% end %>
								<%= button_to reimbursement_path(reimbursement), method: :delete do %>
									<i class="fa fa-trash-o"></i>
								<% end %>
							</td>
						</tr>
					<% end %>
				<%else%>
					<tr>
						<td colspan="8">
							No reimbursements found
						</td>
					</tr>
				<%end%>
			</tbody>
		</table>
		<%= will_paginate reimbursements%>
	</div>
</div>

<script type="text/javascript">
	function download_receipt(e){
	  const reimbursement_id = e.getAttribute('reimbursement-id');
		const url = `/reimbursements/${reimbursement_id}/download`
	  const xhr = new XMLHttpRequest();
	  xhr.open("POST", url);
	  xhr.setRequestHeader("Content-type", "application/json");
	  xhr.send();
	}
</script>

<style type="text/css">
	.actions a{
 		padding: 3px;
 	}
 	.actions i{
 		width: 20px;
 		height: 20px;
 	}
</style>

app/views/reimbursements/edit.html.erb
<%= render 'form' %>

app/views/reimbursements/index.html.erb
<%= render :partial => 'list', locals: {reimbursements: @reimbursements} %>

app/views/reimbursements/new.html.erb
<%= render 'form' %>

app/views/reimbursements/show.html.erb
<h1>Reimbursements#show</h1>
<p>Find me in app/views/reimbursements/show.html.erb</p>